sqs-provider: aws
sqs-region: eu-west-2

search-queue:
  sqs-queue: ${search.queue}
  access-key-id: ${search.queue.access.key.id}
  secret-access-key: ${search.queue.secret.access.key}

search-dlq:
  sqs-queue: ${search.dlq.queue}
  access-key-id: ${search.dlq.access.key.id}
  secret-access-key: ${search.dlq.secret.access.key}

audit-queue:
  sqs-queue: ${audit.queue}
  access-key-id: ${audit.queue.access.key.id}
  secret-access-key: ${audit.queue.secret.access.key}

audit-dlq:
  sqs-queue: ${audit.dlq.queue}
  access-key-id: ${audit.dlq.access.key.id}
  secret-access-key: ${audit.dlq.secret.access.key}

document-queue:
  sqs-queue: ${document.queue}
  access-key-id: ${document.queue.access.key.id}
  secret-access-key: ${document.queue.secret.access.key}

document-dlq:
  sqs-queue: ${document.dlq.queue}
  access-key-id: ${document.dlq.access.key.id}
  secret-access-key: ${document.dlq.secret.access.key}

notify-queue:
  sqs-queue: ${notify.queue}
  access-key-id: ${notify.queue.access.key.id}
  secret-access-key: ${notify.queue.secret.access.key}

notify-dlq:
  sqs-queue: ${notify.dlq.queue}
  access-key-id: ${notify.dlq.access.key.id}
  secret-access-key: ${notify.dlq.secret.access.key}
